# -*- coding: utf-8 -*-
"""KNN_Mnist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k2ueEMJ26zcmbql-jCIho9jwdkqdmVkZ
"""

from keras.datasets import mnist
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#load / split data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

#turn img into grayscale
plt.gray()

plt.imshow(x_train[0])

plt.imshow(x_test[0])

#reshape to fit in model
x_train = x_train.reshape(len(x_train), -1)

x_train.shape

#reshape to fit in model
x_test = x_test.reshape(len(x_test), -1)

x_test.shape

#convert to float32 and normalize data
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train = x_train / 255.0
x_test = x_test / 255.0

KNN = KNeighborsClassifier(n_neighbors= 4)

KNN.fit(x_train, y_train)

KNN_predict = KNN.predict(x_test)

KNN_predict.shape

KNN_accuracy = accuracy_score(y_test, KNN_predict)

KNN_accuracy

